version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/taskflow
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - taskflow-network
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_DATABASE=taskflow
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - taskflow-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - taskflow-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  taskflow-network:
    driver: bridge 