version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://taskflow:taskflow@db:5432/taskflow
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - taskflow-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=taskflow
      - POSTGRES_USER=taskflow
      - POSTGRES_PASSWORD=taskflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - taskflow-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - taskflow-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  taskflow-network:
    driver: bridge 