name: CI Pipeline

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run linting with flake8
      run: |
        flake8 app/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run code formatting check with black
      run: |
        black --check --diff app/ tests/
    
    - name: Run Security Scans
      run: |
        pip install safety bandit
        safety check --json --output safety-report.json || true
        bandit -r app/ -f json -o bandit-report.json || true
        echo "Security scans completed"
    
    - name: Run tests with pytest
      env:
        DATABASE_URL: sqlite:///test.db
        SECRET_KEY: test-secret-key
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/ -v --tb=short --cov=app --cov-report=xml --cov-report=term-missing